server:
  port: 8765
spring:
  application:
    name: admin-service
  boot:
    admin:
      discovery:
        ignored-services: gateway-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: info,metrics,health